// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class MonsterJumperServices
{
        public const string achievement_apprentice_jumper = "CgkIu6mx_qkPEAIQDA"; // <GPGSID>
        public const string achievement_master_jumper = "CgkIu6mx_qkPEAIQDw"; // <GPGSID>
        public const string achievement_collect_200_coins = "CgkIu6mx_qkPEAIQAQ"; // <GPGSID>
        public const string leaderboard_current_coins = "CgkIu6mx_qkPEAIQEg"; // <GPGSID>
        public const string achievement_legendary_jumper = "CgkIu6mx_qkPEAIQEA"; // <GPGSID>
        public const string achievement_max_upgrade = "CgkIu6mx_qkPEAIQCw"; // <GPGSID>
        public const string achievement_jaime_unlocked = "CgkIu6mx_qkPEAIQAw"; // <GPGSID>
        public const string leaderboard_ranking = "CgkIu6mx_qkPEAIQCg"; // <GPGSID>
        public const string achievement_chester_unlocked = "CgkIu6mx_qkPEAIQBQ"; // <GPGSID>
        public const string achievement_cash_knight = "CgkIu6mx_qkPEAIQEQ"; // <GPGSID>
        public const string achievement_first_purchase = "CgkIu6mx_qkPEAIQAg"; // <GPGSID>
        public const string achievement_gerard_unlocked = "CgkIu6mx_qkPEAIQCA"; // <GPGSID>
        public const string achievement_castle_dungeon_unlocked = "CgkIu6mx_qkPEAIQCQ"; // <GPGSID>
        public const string achievement_adept_jumper = "CgkIu6mx_qkPEAIQDQ"; // <GPGSID>
        public const string achievement_expert_jumper = "CgkIu6mx_qkPEAIQDg"; // <GPGSID>
        public const string achievement_billy_unlocked = "CgkIu6mx_qkPEAIQBA"; // <GPGSID>
        public const string achievement_christmas_map_unlocked = "CgkIu6mx_qkPEAIQBg"; // <GPGSID>
        public const string achievement_first_jump = "CgkIu6mx_qkPEAIQAA"; // <GPGSID>
        public const string achievement_dullahan_unlocked = "CgkIu6mx_qkPEAIQBw"; // <GPGSID>
    //Ainda n�o utiizamos o Coins Rank
}

